### ISSUE TITLE
Missing File or Directory Errors if no uploads/landing-pages/templates directory exists

### ISSUE THREAD

**Issue by ITedInnovator** [inboundnow/inbound-pro#172]
The plugin throws an error when the user activates the plugin if the uploads directory does not exist.

Therefore, for non-developers it would be a good idea to note on the Download page that users should create the directory structure wp-content/uploads/landing-pages/templates .

**Comment by atwellpub** [comment]
Hi, this might be something I can fix. Do you happen to have a copy of the error message in your PHP error logs?
