### ISSUE TITLE
Datepicker in cta template

### ISSUE THREAD

**Issue by Keomoniroath** [inboundnow/inbound-pro#174]
I tried to put a datepicker as type of field but it doesn't work. 
There is no error just that nothing is displayed : 

![image](https://user-images.githubusercontent.com/29626942/32234220-7beebe78-be5c-11e7-95a1-4c6680e9d3a2.png)

Thanks

**Comment by cedrox** [comment]
FYI, We try to use this on IIS


/* Date Picker Example */     array(        'label' => 'Date Picker Label',        'description' => "Date Picker Description",        'id'  => 'date_picker', // called in template's index.php file with lp_get_value($post, $key, 'date-picker');        'type'  => 'datepicker',        'default'  => '2013-12-27',        'context'  => 'normal'        ), |   | /* Date Picker Example */ |   | array( |   | 'label' => 'Date Picker Label', |   | 'description' => "Date Picker Description", |   | 'id'  => 'date_picker', // called in template's index.php file with lp_get_value($post, $key, 'date-picker'); |   | 'type'  => 'datepicker', |   | 'default'  => '2013-12-27', |   | 'context'  => 'normal' |   | ),
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | /* Date Picker Example */
  | array(
  | 'label' => 'Date Picker Label',
  | 'description' => "Date Picker Description",
  | 'id'  => 'date_picker', // called in template's index.php file with lp_get_value($post, $key, 'date-picker');
  | 'type'  => 'datepicker',
  | 'default'  => '2013-12-27',
  | 'context'  => 'normal'
  | ),

**Comment by atwellpub** [comment]
I made a commit to the develop branch that should restore this setting. Will you guys confirm it's a fix?

**Comment by Keomoniroath** [comment]
Thank you very much @atwellpub, it works !

**Comment by cedrox** [comment]
Thanks a lot @atwellpub !! ;)
