### ISSUE TITLE
Native CTA

### ISSUE THREAD

**Issue by cedrox** [inboundnow/inbound-pro#175]
[Feature request]
We would like to have the ability to include CTA in the grid (archive.php for exemple). The render will be close from a "native" item but will display a cta. 
We begin to hard code that by using WP Query and mix cta and post but I am not sure this is the best option. What do you think so ? 
Included code :
_In category-business.php_ 

?php
$lastArgs = array(
	'posts_per_page' => '6',
	'post__not_in' => $id_list,
	'category_name' => 'business'
	);

$ctaArgs = array(
	'posts_per_page' => '2', //Je demande plus de post (CTA) dans le cas ou un post (CTA) n'aurait pas de thumbnail. (il m'en faut au moins 1).
	'post_type' => 'wp-call-to-action',
	'tax_query' => array(
		'relation' => 'AND', //Pour être affiché l'éditeur doit avoir coché au moins les catégories 'business' et 'native'
		array(
			'taxonomy' => 'wp_call_to_action_category',
			'field'    => 'slug',
			'terms'    => array( 'business' ),
		),
		 array(
			'taxonomy' => 'wp_call_to_action_category',
		 	'field'    => 'slug',
		 	'terms'    => array( 'native-cta' ),
		 ),
	),
);

$last = new WP_Query($lastArgs);
$cta = new WP_Query($ctaArgs);
?>

apply_filters('custom_grid_CTA', $last, $cta); 

// call situated in custom_grid_CTA fonction in functions.php.

function show_posts( $post, $max, $type ) { 
    if ($post->have_posts()):
		$count = 0;
		while (($post->have_posts()) && ($count != $max)):
			$post->the_post();	
			if (has_post_thumbnail()) {
				if ($type == 'cta') {
					get_template_part( 'template-parts/post/cta-grid', get_post_format());
				} else if ($type == 'post') {
					get_template_part( 'template-parts/post/grid', get_post_format());
				}
				$count = $count + 1;
			}
		endwhile;
		?>
	<?php
	endif;
    return true;
}
add_filter( 'show_posts', 'show_posts', 10, 3 );

function render_row_grid() { 
	?>
	</div>
		<div class="m-content-placement" data-grid="col-12">
<?php
    return 'true';
}
add_filter( 'render_row_grid', 'render_row_grid', 10, 0 );

//grid-3-1-CTA-1
function custom_grid_CTA($last, $cta) { 
	apply_filters( 'show_posts', $last, 3, 'post' );
	apply_filters( 'render_row_grid', 'value' );  // 'value' isuseless, 
	apply_filters( 'show_posts', $last, 1, 'post' );
	if ($cta->have_posts()) {
		apply_filters( 'show_posts', $cta, 1, 'cta' );
		apply_filters( 'show_posts', $last, 1, 'post' );
	} else {
		apply_filters( 'show_posts', $last, 2, 'post' );
	}
	apply_filters( 'render_row_grid', 'value' ); 
}
add_filter( 'custom_grid_CTA', 'custom_grid_CTA', 10, 2 );

Thanks

**Comment by atwellpub** [comment]
Drawing from the wp_posts table directly is a wild idea. I'm not sure how it would work. Your code looks like it's on track. I'm worried about how the render will be handled. It could work perfectly. 

How I would have done it is I would add a sidebar to the archive page and render it with a static or dynamic CTA and then hide it. I'd then use JS to append it as an item into the archive feed. I'd have to do some basic math to find out the best place to put it.

Your way sounds more interesting though.

**Comment by cedrox** [comment]
2 problems with my way : 
1. Inbound url are not render as we render meta (and mabye other thing that I don't know about what you do at rendering)
2. It's hard to manadge cta order in the post flow.

Maybe I am wrong to go this way as I concider CTA as data and not as piece of html. I want to have a generic cta and control the rendering in the theme (witch is not the case of a basic user)

Thanks

**Comment by atwellpub** [comment]
I agree on the order. You could do two separate queries on your archive page. One for CTAs one for the regular loop. Then every Xth iteration you could insert a CTA from your CTA query as an additional item. All you need to render the CTA in a container is the CTA ID and then you could craft a shortcode like this:

````
echo do_shortcode('[cta id="'.$some_cta_id.'"]); 
````

**Comment by kevin-colleter** [comment]
Hello,

We are trying to deploy the same CTA but with **different render**.
So we want to use the URL Inbound, with Views and Conversions. The only one solution we found is to customize your shortcode with CSS. It will be better to use the WP rendering with the benefits of your tracking features (Views/Conversions).

Solution of the previous problem:
We are going to use the **pre_get_posts** (it gives developpers access to the $query object by reference). We will add some CTAs in the result query ! 
Then in archives.php we will use your shortcode :  _echo do_shortcode('[cta id="'.$some_cta_id.'"]);_
And we'll modify it with CSS for a good rendering.

**Comment by atwellpub** [comment]
Very good that sounds like a great plan. 

Let me know if I can help further.
