### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by cedrox** [inboundnow/inbound-pro#177]
In the GDPR context (https://ico.org.uk/for-organisations/data-protection-reform/overview-of-the-gdpr/principles/), we want to be sure that data is anonymous. Can you confirm ? Is it possible to get user from lead_uid for exemple ?

**Comment by atwellpub** [comment]
A personal with DB access could use the lead_uid to pull up at least one session of one lead. But that assumes DB access. Without DB access the lead_uid is as useless as a wordpress user ID.

**Comment by cedrox** [comment]
Please let me add some comment / questions : 
- Data should be anonymized (Can you cross data between WP user datatable and inbound tracking system or is it only via other inbound module (inbound lead...) ?) .
-  GDPR imposes on us that we collect consent before collecting personal data. Is it possible to notify  plugin not to collect IP before the user accept the cookie consent ?
I know that this is EU case but I think it's always nice to have better control on this...

**Comment by atwellpub** [comment]
We can link wp_users to lead profiles inside of wp_posts by comparing email addresses. If a visitor never fills out a tracked form then their data remain anonymous. 

I'll not add any consent/eu compliance popups. \ But it could be listed inside or around a form that submitting data into a form is consenting. Or you could gate consent using a 3rd party compliance tool.
