### ISSUE TITLE
Incorrect Verbiage in Changelog - sanitations should be sanitization

### ISSUE THREAD

**Issue by garrett-eclipse** [inboundnow/inbound-pro#179]
Hello,

Just translating for en_CA and wanted to flag that sanitations was the incorrect word and you're looking for sanitization.

Permalink - https://translate.wordpress.org/projects/wp-plugins/landing-pages/dev-readme/en-ca/default?filters%5Boriginal_id%5D=5356863
Should be - Adding sanitization

Permalink - https://translate.wordpress.org/projects/wp-plugins/leads/dev-readme/en-ca/default?filters%5Boriginal_id%5D=5356758
Should be - Adding sanitization for better security.

Permalink - https://translate.wordpress.org/projects/wp-plugins/cta/dev-readme/en-ca/default?filters%5Boriginal_id%5D=5356947
Should be - Adding sanitization for better security.

Hope that helps,
Cheers

**Comment by atwellpub** [comment]
Hi Garrett,

Very good thank you! 

My spelling is the worst! 

I've got these updated in my dev files and they'll be corrected in the next release series. 

Pleasant regards and anytime,
Hudson Atwell

**Comment by garrett-eclipse** [comment]
Thanks Hudson, all the best
