### ISSUE TITLE
404 dependencies in bitnami VM | Admin / Create new post

### ISSUE THREAD

**Issue by cedrox** [inboundnow/inbound-pro#183]
Hello, 
Dependencies loaded from New post creation page on Back Office don't work properly. 

Localhost 
 array(3) {
  ["path"]=>
  string(140) "C:\Users\me\Source\wp-content\plugins\cta\shared\assets\plugins\advanced-custom-fields-font-awesome/"
  ["dir"]=>
  string(82) "/wp-content/plugins/cta/shared/assets/plugins/advanced-custom-fields-font-awesome/"
  ["version"]=>
  string(3) "1.5"
}

bitnami VM
>> wp-content folder is different form core folders... 

array(3) {
  ["path"]=>
  string(100) "/bitnami/wordpress/wp-content/plugins/cta/shared/assets/plugins/advanced-custom-fields-font-awesome/"
  ["dir"]=>
  string(100) "/bitnami/wordpress/wp-content/plugins/cta/shared/assets/plugins/advanced-custom-fields-font-awesome/"
  ["version"]=>
  string(3) "1.5"
}

generete url like this 
https://baseUrl/**bitnami/wordpress**/wp-content/plugins/cta/shared/assets/plugins/advanced-custom-fields-font-awesome/css/select2.css?ver=1.5

I try to upgrade dependancy management like this 

![image](https://user-images.githubusercontent.com/10764310/37471067-3b590068-2869-11e8-8451-abb147adf9ba.png)

but I still have trouble to integrate
/wp-content/plugins/cta/js/input.min.js?ver=4.4.12

because it should load dynamically I think...

Correct path : 
/wp-content/plugins/cta/shared/assets/plugins/advanced-custom-fields/js/input.min.js

Thanks

**Comment by atwellpub** [comment]
I'm testing a possible fix on this branch here if you'd like to download it and test it:
https://github.com/inboundnow/inbound-pro/tree/ACF_FontAwesome

Also I referenced my commit up top so you can see my changes.
