### ISSUE TITLE
Last Character Dropped in Emails "From" name

### ISSUE THREAD

**Issue by travispflanz** [inboundnow/inbound-pro#185]
The last character is being dropped in the From name when sending bulk emails.

Screenshot - https://i.imgur.com/Yl6DYCI.png - Should be "Travis at Search Centered"

When I add a *space* *dot* in the From field - https://i.imgur.com/4bvorGh.png - The email comes through with the From name as expected - https://i.imgur.com/AWqwg9T.png

**Comment by atwellpub** [comment]
Very strange. 

I just tested and the full From Name came through:
https://www.screencast.com/t/G3raGT65uEb
https://www.screencast.com/t/LHMWdjpPk3X

Can you repeat the issue on a different wp instance / different server?

**Comment by travispflanz** [comment]
I tested on kcdogclub.com and it did not have the problem with dropping the last character. On kcdogclub.com, I have it setup with SparkPost.

On searchcentered.com (the site in the first message), I use wp_mail(), but I use Send Emails with Mandrill (https://wordpress.org/plugins/send-emails-with-mandrill/) to takeover the wp_mail function. 

As a note - The last character does not drop in emails sent through Gravity Forms on this site

**Comment by atwellpub** [comment]
I ran my tests with wp_mail() locally, setup through POSTMANSMTP. Will you try temp disabling the Mandrill handler?

**Comment by travispflanz** [comment]
I disabled Send Emails with Mandrill and the last character was still dropped sending with wp_mail()

**Comment by travispflanz** [comment]
Fixed with new update
