### ISSUE TITLE
Reducing impact on admin-ajax.php

### ISSUE THREAD

**Issue by lordmatt** [inboundnow/inbound-pro#187]
There are two calls that are slaughtering my site's waterfall for speed. By hogging POST admin-ajax.php for about 4 seconds each.

* The first is: cta_get_variation | load_plugins ... calls-to-action.php
* The second is: inbound_track_lead

They return 1B and 0 respectively.

From this, I assume they are information gathering rather than information sending. At least inbound_track_lead is. I have a fix but not enough knowledge of the codebase to suggest where it should go.

I got my time to the first byte right down (and started loading assets sooner) by hooking just after head and sending it on its way with an `ob_flush();`. What I am proposing is that one or both could, after preparing whatever return data is needed, return the response, `ob_flush();` to boot it out the door and then get back to making records after? Is that doable or do we surrender focus/control when we return a response?

If this works, and I have every confidence it would, inbound would be faster with a smaller footprint on site loading times.

**Comment by lordmatt** [comment]
Looking through the code, it seems that the AJAx listeners end with an OK header and then terminates. So it seems that PHP might fail to close the connection. This is **not** a bug with inbound but it is something that could be worked around. A `ob_flush();` and/or `ob_end_flush();` before terminating is the usual solution to a connection that hangs which my first instinct.

**Comment by atwellpub** [comment]
Would you be interested in scheduling a call to talk this over?
