### ISSUE TITLE
Add New displays a blank page

### ISSUE THREAD

**Issue by tonyclemmey** [inboundnow/inbound-pro#189]
Hello,

I'm wondering if anyone has experienced the same or has an idea of what is causing this issue.

I have installed the Inbound Pro plugin to WordPress and connected API key. I have all elements showing in dashboard menu Inbound Pro, Landing Pages, Call to actions etc and I can access everything such as settings and overview of landing pages, call to actions which include examples and I can go to edit these but when trying to "add new" on landing pages or call to actions I get nothing but an empty blank page, no fields or options showing.

Also on the existing example or clone of a landing page, when editing the choose another template button also brings up nothing button an empty blank page.

I am not using any other custom post type plugins and default pages and posts "add new" all work fine.

Any help would be much appreciated.

<img width="1043" alt="Screenshot 2019-10-23 at 07 30 05" src="https://user-images.githubusercontent.com/26121527/67364867-51d79e80-f568-11e9-935c-cd9686297620.png">
<img width="1078" alt="Screenshot 2019-10-23 at 07 29 43" src="https://user-images.githubusercontent.com/26121527/67364868-51d79e80-f568-11e9-960c-ca79e562cd14.png">

**Comment by atwellpub** [comment]
Hi Tony, 

I just checked on my WPEngine install and was able to access those pages. Will you head into wp-admin->Tools->Site Health and click the Info tab and then click `Copy Site Info to Clipboard` and then paste the contents here as a new comment? 

Also setting the WP_DEBUG value in wp-config.php to TRUE may display the underlying error that is breaking that page. If you can get the error to show then can you screenshot it and also share it here?

**Comment by tonyclemmey** [comment]
Hi Hudson,

Thank you for your reply. WP_DEBUG didn't bring up any errors on screen although I have set the following

`ini_set('display_errors','On');
ini_set('error_reporting', E_ALL );
define('WP_DEBUG', true); 
define('WP_DEBUG_DISPLAY', true); 

define('WP_DEBUG_LOG', true);
define('SCRIPT_DEBUG', true);`

the debug.log only displays the following

`[24-Oct-2019 02:35:34 UTC] PHP Notice:  Undefined variable: title in ..../wp-content/plugins/stars-testimonials-with-slider-and-masonry-grid/plugin.class.php on line 395`

I have tried to uninstall the plugin and remove/clean database/tables (WP-Optimize) for the plugin that is no longer installed and then attempt to install the plugin again but no luck getting past the issues.

I also had set both versions of PHP 7.1 and 7.3.9

<img width="870" alt="Screenshot 2019-10-24 at 02 36 18" src="https://user-images.githubusercontent.com/26121527/67448094-e9db9380-f60d-11e9-9b29-40e5553d72ed.png">
<img width="861" alt="Screenshot 2019-10-24 at 02 27 06" src="https://user-images.githubusercontent.com/26121527/67448107-ef38de00-f60d-11e9-89c8-6ddfe5c575d3.png">
<img width="877" alt="Screenshot 2019-10-24 at 02 27 44" src="https://user-images.githubusercontent.com/26121527/67448116-f364fb80-f60d-11e9-81f9-411906c06a27.png">

**Comment by tonyclemmey** [comment]
Site Info
```

### wp-core ###

version: 5.2.4
site_language: en_GB
user_language: en_GB
permalink: /%category%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 61
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/admin/public_html/example.com
wordpress_size: 54.79 MB (57452482 bytes)
uploads_path: /home/admin/public_html/example.com/wp-content/uploads
uploads_size: 138.02 MB (144723529 bytes)
themes_path: /home/admin/public_html/example.com/wp-content/themes
themes_size: 3.39 MB (3554313 bytes)
plugins_path: /home/admin/public_html/example.com/wp-content/plugins
plugins_size: 294.09 MB (308374020 bytes)
database_size: 10.08 MB (10571776 bytes)
total_size: 500.37 MB (524676120 bytes)

### wp-active-theme ###

name: Astra
version: 1.6.4
author: Brainstorm Force
author_website: https://wpastra.com/about/
parent_theme: none
theme_features: astra_hooks, align-wide, automatic-feed-links, title-tag, post-thumbnails, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets, menus
theme_path: /home/admin/public_html/example.com/wp-content/themes/astra

### wp-mu-plugins (1) ###

fast-ajax.php: author: (undefined), version: (undefined)

### wp-plugins-active (70) ###

Add Categories to Pages.: version: 1.1, author: a.ankit
Advanced Order Export For WooCommerce: version: 2.1.1, author: AlgolPlus
AJAX Search for WooCommerce: version: 1.3.3, author: Damian Góra
ARVE Advanced Responsive Video Embedder: version: 8.10.4, author: Nicolas Jonas
Astra Hooks: version: 1.0.1, author: Brainstorm Force
Astra Pro: version: 1.6.4, author: Brainstorm Force
Astra Starter Sites – Elementor, Beaver Builder & Gutenberg Templates: version: 1.2.12, author: Brainstorm Force
Astra Theme Visual Hooks: version: 1.1.0, author: Brainstorm Force
Autoclear Autoptimize Cache: version: 1.0.0, author: Theme Surgeons
Autoptimize: version: 2.5.1, author: Frank Goossens (futtta)
Beaver Builder Plugin (Lite Version): version: 2.2.0.6, author: The Beaver Builder Team
Capability Manager Enhanced: version: 1.7.5, author: PublishPress
Classic Editor: version: 1.4, author: WordPress Contributors
Code Snippets: version: 2.13.2, author: Shea Bunge
Contact Form 7: version: 5.1.1, author: Takayuki Miyoshi
Contact Form 7 - reCaptcha v2: version: 1.2.0, author: IQComputing
Crelly Slider: version: 1.3.4, author: Fabio Rinaldi
Custom Adobe Fonts (Typekit): version: 1.0.11, author: Brainstorm Force
Custom Fonts: version: 1.0.7, author: Brainstorm Force
Customizer Search: version: 1.1.2, author: Brainstorm Force
Duplicator: version: 1.3.14, author: Snap Creek
Easy Google Fonts: version: 1.4.4, author: Titanium Themes
Easy Updates Manager: version: 8.0.3, author: Easy Updates Manager Team
Enable Media Replace: version: 3.2.9, author: ShortPixel
Enhanced Media Library: version: 2.7.2, author: wpUXsolutions
Favicon by RealFaviconGenerator: version: 1.3.15, author: Philippe Bernard
Fitness Schedule: version: 1.3.5, author: Maxime BERNARD-JACQUET
GDPR Cookie Compliance: version: 2.1.1, author: Moove Agency
Google Analytics for WordPress by MonsterInsights: version: 7.7.1, author: MonsterInsights
Hummingbird: version: 1.9.3, author: WPMU DEV
If Menu - Visibility control for menu items: version: 0.12.2, author: Layered
Inbound Now PRO: version: 1.9.9.7.5, author: InboundWP LLC
Loginizer: version: 1.4.1, author: Raj Kothari
Menu Icons: version: 0.11.4, author: ThemeIsle
Official Facebook Pixel: version: 1.7.25, author: Facebook
Photo Gallery: version: 1.5.20, author: Photo Gallery Team
Podamibe Simple Footer Widget Area: version: 2.0.7, author: Podamibe Nepal
Remove Yoast SEO Comments: version: 3.1, author: Mitch
reSmush.it Image Optimizer: version: 0.1.22, author: reSmush.it
Responsive Facebook Page Plugin: version: 1.6.3, author: Cameron Jones
Responsive Pricing Table: version: 5.0.4, author: WP Darko
Reveal IDs: version: 1.5.3, author: Oliver Schlöbe
Schema: version: 1.7.4, author: Hesham
SG Optimizer: version: 5.1.1, author: SiteGround
Shortcoder: version: 4.3, author: Aakash Chakravarthy
Stars Testimonials: version: 3.0.4, author: Premio
TablePress: version: 1.9.2, author: Tobias Bäthge
Terms and Conditions Popup for WooCommerce: version: 3.5, author: BeRocket
Two Factor Authentication: version: 1.5.2, author: David Nutbourne + David Anderson, original plugin by Oskar Hane
Ultimate Addons for Beaver Builder - Lite: version: 1.2.4, author: Brainstorm Force
Ultimate Addons for Gutenberg: version: 1.12.4, author: Brainstorm Force
Ultimate FAQ: version: 1.8.19, author: Etoile Web Design
Webcraftic Disable Admin Notices Individually: version: 1.0.6, author: Webcraftic <wordpress.webraftic@gmail.com>
Woo Checkout Field Editor Pro: version: 1.2.8, author: ThemeHiGH
WooCommerce: version: 3.6.1, author: Automattic
WooCommerce Accommodation Bookings: version: 1.1.8, author: WooCommerce
WooCommerce Bookings: version: 1.12.0, author: Automattic
WooCommerce Checkout Manager: version: 4.3, author: Visser Labs
WooCommerce Max Quantity: version: 1.5.1, author: Isabel Castillo
WooCommerce Min/Max Quantities: version: 2.4.1, author: WooCommerce
WooCommerce Stripe Gateway: version: 4.1.12, author: WooCommerce
WooCommerce Subscriptions: version: 2.4.0, author: Prospress Inc.
WordPress Importer: version: 0.6.4, author: wordpressdotorg
WP-Optimize: version: 2.2.12, author: David Anderson, Ruhani Rabin, Team Updraft
WP Content Copy Protection & No Right Click: version: 1.6.2, author: wp-buy
WP Meta SEO: version: 4.0.3, author: JoomUnited
WPS Hide Login: version: 1.5.2.2, author: WPServeur, NicolasKulka, tabrisrp
WP SVG images: version: 3.0, author: KubiQ
XT Woo Floating Cart: version: 1.2.9, author: XplodedThemes
Yoast SEO: version: 11.5, author: Team Yoast

### wp-plugins-inactive (9) ###

ACF Flexible Layouts Manager: version: 1.1.6, author: Valentin PELLEGRIN
Advanced Custom Fields: Extended: version: 0.8, author: ACF Extended
Advanced Custom Fields Pro: version: 5.8.1, author: Elliot Condon
PluginOps Landing Page Builder: version: 1.4.7.3, author: PluginOps
Prevent Browser Caching: version: 2.3, author: Kostya Tereshchuk
SmartCrawl: version: 2.2.4.1, author: WPMU DEV
UpdraftPlus - Backup/Restore: version: 1.16.6, author: UpdraftPlus.Com, DavidAnderson
WooCommerce Bulk Discount: version: 2.4.5, author: Rene Puchinger
WP Facebook Review Slider: version: 7.5, author: LJ Apps

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 3.12.18-clouder0 x86_64
httpd_software: Apache
php_version: 7.3.9 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.59.0 OpenSSL/1.0.2r
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.40-84.0-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/admin/public_html/example.com/wp-content
WP_PLUGIN_DIR: /home/admin/public_html/example.com/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable
```

**Comment by atwellpub** [comment]
Just to confirm, you tried uninstalling `stars-testimonials-with-slider-and-masonry-grid` which gave the PHP notice, and no other error message would display/record on `add new` page and it's still breaking?

The PHP notice error isn't strong enough to cause a fatal error--- and the screenshots suggest there is another fatal happening that prevents the rendering of the UI. 

I'd also recommend disabling all plugins but Inbound Pro and seeing if the error persists. If it stops, try activating every plugin one by one to discover which plugin is the problem plugin

**Comment by tonyclemmey** [comment]
I would agree I don't think the PHP notice error should be related to the issue, unfortunately, its a live site so I do not wish to be turning off plugins. I would have to clone the site and then see what plugin could be conflicting with it?

For now, I think I will look at setting up a subdomain with a fresh wp install and try out the Inbound pro features that way? 

I just want to create a custom HTML landing page template with ACF fields I'm assuming this is possible? and the landing page would be a custom post type? Template could be used with ACF fields to enter the content for each new landing page?

**Comment by atwellpub** [comment]
Hi Tony, 

Exactly. You could use ACF to create custom templates for landing pages. There's a little bit of intergration/setup work behind it. Documentation for this outfit has never been excellent, but here's a good start:

https://github.com/wp-plugins/leads/blob/master/shared/docs/how.to.create.landing.page.templates.using.ACF.md
