### ISSUE TITLE
Reliance on PHP Sessions

### ISSUE THREAD

**Issue by artibyrd** [inboundnow/inbound-pro#190]
Since WP 4.9 use of PHP sessions in WordPress has been disabled, but Inbound Pro continues to use PHP sessions in its current version.  This throws 2 critical issues on a WP Site Health check: “The REST API encountered an error” and “Your site could not complete a loopback request” when the Inbound Pro plugin is enabled.

I have been able to work around this by using the WordPress Native PHP Sessions plugin:
https://wordpress.org/plugins/wp-native-php-sessions/

Will Inbound Pro be updated to either remove reliance on sessions or include functionality similar to this plugin natively in order to address how WordPress handles PHP sessions now?

**Comment by atwellpub** [comment]
Hi @artibyrd , 

Very good questions. It's something I'm having to learn more about. 

I don't think I will be able to change the current system's dependency on sessions. I think we are only using session vars Admin side to keep track of which variation a user is editing. 

I also think that sessions are still enabled for most PHP environments. For example, I've never noticed issues on DreamHost or WPEngine. A solution may be to enable sessions at the PHP level. 

I'm rebuilding Inbound Now products in my spare time, so possibly, in 2020, there will be a new iteration that has zero dependencies on sessions.

**Comment by artibyrd** [comment]
I encountered these issues out of the box using the latest Bitnami WordPress VM image on Google Cloud Platform.  To be fair, Inbound Pro appeared to still be working normally, and without looking at the WP Site Health Check I would have assumed there were no issues at all.
I have _several_ other critical plugins that also similarly utilize PHP sessions and the plugin I mentioned has satisfactorily resolved this issue for my needs personally, but this issue is likely to be reported more commonly in the future as more people update their servers - especially since the Site Health Check seems to be built into the latest WP versions!

**Comment by sciencewhiz** [comment]
Thanks the pointer to WordPress Native PHP Sessions plugin. I installed it and it fixed the loopback request issue, but I still see the active PHP session issue.
