### ISSUE TITLE
GeoIP Detection - Maxmind GeoIP Lite City

### ISSUE THREAD

**Issue by travispflanz** [inboundnow/inbound-pro#191]
Maxmind has changed the way the database is accessed (https://dev.maxmind.com/geoip/geoip2/geolite2/) meaning the database is not being updated in Inbound Pro anymore

**Comment by atwellpub** [comment]
I just ran an update that may fix this. Needs to be tested though.

**Comment by travispflanz** [comment]
I have tested by creating a MaxMind license key for GeoIP Update 3.1.1 or above and I received this message. 
Screenshot 1 - https://i.imgur.com/c0Ws8bu.png 
Screenshot 2 - https://i.imgur.com/uSCUIod.png

Looking at /uploads/inbound-pro/extensions/inbound-geodetect/assets/geoip-detect/geoip-detect.php it appears Inbound Pro is using GeoIP Update version 3.0.1 (I may be wrong) - https://i.imgur.com/aqyEcEc.png

So, I created a MaxMind license key for GeoIP Update 3.0.1 or lower and received this message
Screenshot 1 - https://i.imgur.com/VDGejps.png
Screenshot 2 - https://i.imgur.com/HjyiTZc.png

**Comment by atwellpub** [comment]
Yes, am using this asset:
https://wordpress.org/plugins/geoip-detect/

Which 3.0.1 is currently being served. 

Not sure why the update feature is not working. Will have to give this another test tomorrow.

**Comment by travispflanz** [comment]
I'm sure it's irrelevant, but the "Manual download & update of a Maxmind City or Country database" option does work as expected.

**Comment by atwellpub** [comment]
Nice. That's good news. 

I just tested locally and I had to use the >3.1.1 license key generation in order for the plugin to accept it... although the version plugin I have is <3.1.1. 

Not sure what is going on there. Doesn't look like I can test locally because all my IPs are local IPs. I'm going to try running a test on a live site.

**Comment by atwellpub** [comment]
Although everything sets up well, I get a "you do not have permission to access this service" when I run the test. 

I switched back to the older license key and this time remembered to add my user id and it connected, but same error message on tests. 

I'm probably not going to be able to fix the options page error. Not enough time.

Going to test the manual download and update method.

**Comment by atwellpub** [comment]
Seems the Yellow tree plugin 3.0.1 is it's own plugin version and the 3.1.1 is the MaxMind version. 

So we should in theory be able to use the latest hashed API keys. 

I'm not sure why its not connecting though. 

The Yellow Tree repo issues might hold leads:
https://github.com/yellowtree/geoip-detect/issues

Considering taking the asset down in the meantime and adding the repo publicly to github. What do you think?

**Comment by travispflanz** [comment]
I'm not a dev at all and don't know how to use Github... So...

**Comment by atwellpub** [comment]
https://github.com/inboundnow/inbound-geodetect

**Comment by atwellpub** [comment]
Are you on Discord? I have a network I'm setting up there to keep track with everyone and document work, if you'd like to join and keep me updated with findings. 

https://discord.gg/dXmtHX9

**Comment by travispflanz** [comment]
I've never used it (I already have way too many communication tools/apps/devices to keep track of as it is now), but I accepted the invitation
