### ISSUE TITLE
Lead > Direct Email - default From Email not populating properly

### ISSUE THREAD

**Issue by travispflanz** [inboundnow/inbound-pro#192]
The Reply Email populates as expected.

The error appears to be on line 186 of inbound-pro/core/mailer/classes/class.lead-profile.php

**Comment by travispflanz** [comment]
Just a thought, should the default "From Email" for a "Direct Email" be the same email address that is set in "Default From Email" in /wp-admin/admin.php?page=inbound-pro?

Being that a website may have multiple admins, and all may not have their profile email set to a real/created email address at the domain name, defaulting to the "Default From Email" makes a lot of sense. Then, the default "Reply Email" address for a "Direct Email" should default to the email address set in the admin's profile (as it is currently).

**Comment by klf6890** [comment]
From initial exploration, it looks like maybe the intention for this was to append a sending domain to the truncated email address. The jQuery and such of the from email field references a sending domain field, which doesn't seem to exist any longer on the page or in settings. Without it to append there, it's just placing the truncated piece of the email in the from email field. Haven't had time to work out the best approach given that but hoping to look into it soon!

**Comment by atwellpub** [comment]
Hey, 

@klf6890 @travispflanz 

I made a commit above that may fix this. Needs a test though if one of you wouldn't mind running a replacement on the below file's content and reporting back: 

https://raw.githubusercontent.com/inboundnow/inbound-pro/97be90589b831667aa63b62ef0a25d08f4a0284d/core/mailer/classes/class.lead-profile.php

**Comment by travispflanz** [comment]
After replacing the content from your link to class.lead-profile.php, the From Email is blank by default. Screenshot - https://i.imgur.com/wbtAVW8.png

**Comment by atwellpub** [comment]
Here's an update. I believe I ID'd the bug:
https://raw.githubusercontent.com/inboundnow/inbound-pro/d2cb9da9e63e5c4211fe8098540339a8f8e595c8/core/mailer/classes/class.lead-profile.php

**Comment by travispflanz** [comment]
The logged in user's email address on account is being pulled over now - https://i.imgur.com/D8xl0bZ.png

That said, the user's email address is not an email address on the website's domain, so the email will be rejected per spf, dkim and dmarc settings if sent using the user's email address.

**Comment by atwellpub** [comment]
Got you. 

I'll run more tests tomorrow to get the correct email address in. ttys.

**Comment by atwellpub** [comment]
https://github.com/inboundnow/inbound-pro/commit/a53e9bb31fb24e27d0900510615ffe5da7538f4b

**Comment by atwellpub** [comment]
New file to test:
https://raw.githubusercontent.com/inboundnow/inbound-pro/a53e9bb31fb24e27d0900510615ffe5da7538f4b/core/mailer/classes/class.lead-profile.php

**Comment by travispflanz** [comment]
I have tested The update pulls in the "Default From Name," not the "Default From Email"

**Comment by atwellpub** [comment]
https://raw.githubusercontent.com/inboundnow/inbound-pro/080a28f85bea17d87755b41d1b655eb5b6d28779/core/mailer/classes/class.lead-profile.php

This should be it. Apologies for the run-around.

**Comment by travispflanz** [comment]
Forgot to follow up again. Works as expected now

**Comment by atwellpub** [comment]
Nice. Patch will be included in next release.

**Comment by travispflanz** [comment]
It seems this code may have been overriden or not added to the zip in the account area on inboundnow.com

It is not working now.

I copied the code from https://github.com/inboundnow/inbound-pro/issues/192#issuecomment-593127220 and it is still not working

**Comment by atwellpub** [comment]
Hi @travispflanz 

Just to confirm, you copied the code from this update and there default from email is still not correct?
https://raw.githubusercontent.com/inboundnow/inbound-pro/080a28f85bea17d87755b41d1b655eb5b6d28779/core/mailer/classes/class.lead-profile.php

Warm regards,
Hudson

**Comment by travispflanz** [comment]
I downloaded a fresh copy from my dashboard on inboundnow.com. The default "from" email address did not work. Then, I replaced class.lead-profile.php with the code here - https://raw.githubusercontent.com/inboundnow/inbound-pro/080a28f85bea17d87755b41d1b655eb5b6d28779/core/mailer/classes/class.lead-profile.php

It did not work

**Comment by atwellpub** [comment]
I just pushed 1.9.9.7.7, it's been forever since I've done a release.
