### ISSUE TITLE
wp-lead does not support REST API

### ISSUE THREAD

**Issue by travispflanz** [inboundnow/inbound-pro#194]
I know Inbound Now has been around for a while - before REST API support - but being a marketing automation platform, I think it's important for wp-lead to support REST API, especially since more and more "integrator" SaaS are supporting it. For example, integromat.com, connects to WordPress via REST, unlike Zapier. So, if wp-lead supported the REST API, a whole new world could open up for much easier integration.

RST API support will give a ton of flexibility to be able to create a new lead from a ton of outside sources.

https://github.com/inboundnow/inbound-pro/blob/master/core/shared/classes/class.post-type.wp-lead.php (edit to include correct link)

https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/

**Comment by klf6890** [comment]
The file you mention isn't the correct place it would need to be added. That extends the post type options but the post type itself is declared here:

**https://github.com/inboundnow/inbound-pro/blob/master/core/shared/classes/class.post-type.wp-lead.php**

So, depending on what should be accessible via the REST API, you'd just add 'show_in_rest' => true there, whether it's the post type itself, lists, various taxonomies in the file, etc.

**Comment by travispflanz** [comment]
Thanks, @klf6890! I copy/pasted the wrong link in my original message. I had both open in my browser.

I actually did add REST API support via the functions.php method described here - https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/#adding-rest-api-support-to-existing-content-types

That said, native REST API support would be great for Inbound Now custom post types and custom taxonomies.

**Comment by atwellpub** [comment]
I do not think Inbound Now will get any special attention from me on this topic. 

It's not publicly known, but I have been rebuilding this concept from the ground up for release under a new brand and business organization at a later date. 

I'll provide up-to-date detail to the REST API in this next iteration. 

I'm okay with small changes and bug fixes though.

**Comment by travispflanz** [comment]
Cool. Thanks for the update. As always, I'm excited to see what may come!
