### ISSUE TITLE
Lead not added to Inbound Now via Gravity Forms when Lead Category set to Double Opt-in

### ISSUE THREAD

**Issue by travispflanz** [inboundnow/inbound-pro#195]
It appears Leads are not added to Inbound Now after filling out a Gravity Forms form when the selected list (https://i.imgur.com/EKkvPnO.png) has Doduble Opt-in turned on (https://i.imgur.com/2mHZ3f0.png).

No "Confirm your Subscription" email is sent to the Lead and the Lead does not show up in the Leads list (https://i.imgur.com/005nmIi.png) nor the "Unconfirmed" list (https://i.imgur.com/d3zp62G.png)

**Comment by atwellpub** [comment]
Ack, that's a strong bug. May take me a long while to get to it without a commission. 

For now there's a few more issues open. I'll check out those first.
