### ISSUE TITLE
Only one List can be added to Lead with inbound-api/v1/leads/add lead_lists

### ISSUE THREAD

**Issue by travispflanz** [inboundnow/inbound-pro#196]
Only one List can be added to Lead with inbound-api/v1/leads/add

Documentation suggests multiple lists can be added with lead_lists

Must use inbound-api/v1/leads/modify with add_to_lists to add Lead to multiple lists

Is this correct, or is the documentation incorrect/incomplete? - https://docs.inboundnow.com/guide/lead-api-documentation-v1/

**Comment by travispflanz** [comment]
Also, it seems there are some inaccuracies in the API documentation. Here is another

- Creation of Tracked Link requires id and lead_id. lead_id is not mentioned in the doc. And the doc says that either email OR id is required

**Comment by atwellpub** [comment]
Looking into leads_add() which is run from /leads/add/ and it contains this bit of code:

```
 /* Add lead to lists */
        if (isset($params['lead_lists']) && !is_array($params['lead_lists'])) {
            $params['lead_lists'] = explode(',', $params['lead_lists']);
        }

        if (isset($params['lead_lists']) && self::validate_parameter($params['lead_lists'], 'lead_lists', 'array')) {
            foreach ($params['lead_lists'] as $list_id) {
                Inbound_Leads::add_lead_to_list($lead_id, $list_id);
            }
        }
```
Which in looking,  seems the code is set to loop through list add routines if the `leads_list` param contains list ids separated by commas. 

Are you able to share an example of the data array $params that is not adding multiple lists to a created lead?
