### ISSUE TITLE
PHP Warning for Continue

### ISSUE THREAD

**Issue by mcpacific** [inboundnow/inbound-pro#198]
The PHP error_log shows the following warning:
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/account/public_html/wp-content/plugins/inbound-pro-master/core/leads/classes/class.metaboxes.wp-lead.php on line 1935

To remove the warning, should we update this to 'break' or 'continue 2'?

**Comment by atwellpub** [comment]
Heya we should have a fix to this in the following commit:
https://github.com/inboundnow/inbound-pro/commit/08b782204a5eb9cd74c5a488a73d9e2682602860

But the commit isn't in the latest update, so for now it has to be applied manually.
