### ISSUE TITLE
PHP warning - Uncaught Error: Class 'Leads_Post_Type' not found

### ISSUE THREAD

**Issue by greghard** [inboundnow/inbound-pro#200]
Below is the output:

Error Details
=============
An error of type E_ERROR was caused in line 355 of the file /public/wp-content/plugins/inbound-pro/classes/admin/report-templates/report.impressions.php. Error message: Uncaught Error: Class 'Leads_Post_Type' not found in /public/wp-content/plugins/inbound-pro/classes/admin/report-templates/report.impressions.php:355
Stack trace:
#0 /www/public/wp-content/plugins/inbound-pro/classes/admin/report-templates/report.impressions.php(48): Inbound_Impressions_Report::display_all_visitors()
#1 /www/public/wp-content/plugins/inbound-pro/classes/admin/class.reporting.templates.php(39): Inbound_Impressions_Report::load_template()
#2 /www/public/wp-includes/class-wp-hook.php(287): Inbound_Reporting_Templates::display_template('')
#3 /www/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#4 /www/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /www/public/wp-admin/admin.php(170): do_action('admin_init')
#6 /www/public/wp-admin/index.php(10): require_once('/www/...')

**Comment by atwellpub** [comment]
Hi @greghard 

Quick question, is the Leads component activated? 

Could you describe the steps to reproduce the error?
