### ISSUE TITLE
Can you share a meta_query API example?

### ISSUE THREAD

**Issue by travispflanz** [inboundnow/inbound-pro#202]
I was wondering if you could help me with the format for **meta_query** for a custom lead field? It's not fully detailed in the documentation for inbound-api/v1/leads/ (https://docs.inboundnow.com/guide/lead-api-documentation-v1) and I'm not a dev, so I'm a bit stuck

I am using the API via URL (in Integromat - https://www.integromat.com) and I want to grab a lead's data based on the **Meetup - Member ID** (screenshot - https://i.imgur.com/NIdeZdk.png) in custom lead field **wpleads_meetup_id** (screenshot - https://i.imgur.com/z79rE69.png)

For this example, Meetup - Member ID = **80534812**

https://www.kcdogclub.com/inbound-api/v1/leads?key=ae1ba748dd778fa87078ecXXXXXXX&token=bd207f40ed33b6bd2eaced696bXXXXXX

**Comment by atwellpub** [comment]
Hi @travispflanz 

It's been a very long time since I've worked with the Leads API, but I think it should look something like this:

`$api_url = add_query_arg( array( 
    'key' => self::$key , 
    'token' => self::$token,
    'meta_query' => array(
        'key' => 'wpleads_meetup_id',
        'value' => 80534812
    )
 ), self::$base_api_url . $endpoint );

$results = self::wp_remote_post( $endpoint , self::$data );
`

**Comment by travispflanz** [comment]
Thanks for the reply, but I have no idea how to use that in a URL for the API, which is what I need.

**Comment by atwellpub** [comment]
Are you using code to build your API Request URL?

https://stackoverflow.com/questions/1763508/passing-arrays-as-url-parameter

**Comment by travispflanz** [comment]
Thanks! The decoded version of this URL worked as needed

https://www.kcdogclub.com/inbound-api/v1/leads?key=ae1ba748dd778fa87078ecXXXXXXX&token=bd207f40ed33b6bd2eaced696bXXXXXX&meta_query[][key]=wpleads_meetup_id&meta_query[][value]=80534812

**Comment by atwellpub** [comment]
Nice!
