### ISSUE TITLE
From Field not populating

### ISSUE THREAD

**Issue by mowman33** [inboundnow/inbound-pro#203]
I still use this plugin and upon updating to the latest version (1.9.9.8.4) the emails won't send from the Leads manager. I get an error stating that the From field is missing. Please help

**Comment by atwellpub** [comment]
Hi @mowman33 

Happy to help. 

Would you take a screenshot on where you are having issues? 

Also which email service provider are you using inside Inbound Pro -> Settings? Is it WP_Mail?

**Comment by mowman33** [comment]
I’m using Post SMTP which was custom integrated for me from someone at Codeable.
[cid:image003.jpg@01D6F412.45E93B70]

**Comment by atwellpub** [comment]
I can take a look onsite, if you like. Might take me a 24 hours before I can get to it though. 

hudson@inboundnow.com

**Comment by mowman33** [comment]
That would be fine. You can login at https://topdogsystem.net/backoffice
User: cheks
Pass: g#i1Kc#(^gZT9UrkPUBe$Mdo

Thanks for the help,
John

**Comment by atwellpub** [comment]
Hi John, this is a public issues board. You might need to trash those credentials and resend them to me via email using this email address  `hudson@inboundnow.com` to avoid potential unwanted access. 

Warm regards,
Hudson

**Comment by atwellpub** [comment]
Hi John, 

I took a look and I _believe_ that if you head inside Inbound Pro -> Settings and find the following settings area:
![image](https://user-images.githubusercontent.com/2002207/106205790-ac58a500-6184-11eb-8269-8eae8fc6b170.png)

And populate these, then the direct mail feature should work. 

Would you mind doing this and giving it a test for me?

**Comment by mowman33** [comment]
That worked but I still don’t know why it changed after I updated the plugin.

How do I go about adding additional sites for sending emails? I tried to log into my account by it doesn’t work.

John

________________________________
