### ISSUE TITLE
I hope this is the right place to post this. Your website confused me.

### ISSUE THREAD

**Issue by lordmatt** [inboundnow/inbound-pro#204]
Calls to Action 3.3.11 is adding empty paragraph tags between actual paragraphs on all posts.

**Comment by atwellpub** [comment]
Hi @lordmatt is this for the stand alone plugin that was on the WordPress repo? 

I've retired CTA plugin but it's still included in the Inbound Pro plugin that combines Leads, CTA, Landing Pages all together which can be downloaded here. But it's also retired. I still update it though, and it could be that the issue you're experiencing won't occur from the Inbound Pro plugin. 

re:the issue

empty `<p></p>` tags are being added after every paragraph on a WordPress post when a CTA is being added to that page? Is that correct? 

Or is it that there are paragraphs in the cta that have empty <p> tags added to them?

Would you let me know a little more about how/where the CTAs are being applied?
