### ISSUE TITLE
Gutenberg 10.6.2 causes the Emails component of Inboundnow to stop using email templates

### ISSUE THREAD

**Issue by netflowauditor** [inboundnow/inbound-pro#205]
This issue occurs because of Gutenberg 10.6.2. The prior version of the Gutenberg editor did not cause this behaviour.

The following image reflects the correct behaviour of Inboundnow Emails component. To achieve this working state the Gutenberg 10.6.2 plugin must be deactivated.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/62791190/119458099-0fc69e00-bd45-11eb-86a6-d662eb73fe54.png">

When Gutenberg 10.6.2 is activated the Email, which is delivered via automation and the preview mode both display incorrectly.  The expected template is replaced with the system's website and the expected content is not even displayed within the resulting display/email. The only emails that format correctly are Direct Emails that appear to use the WordPress default.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/62791190/119459414-5072e700-bd46-11eb-82a0-2e65ce242a99.png">

I also reported this bug in https://github.com/WordPress/gutenberg/issues/32130

**Comment by atwellpub** [comment]
hi @netflowauditor 

I increased the priority of one of our filters and it solves the conflict with Gutenberg. 

Pushing a new release now.

**Comment by atwellpub** [comment]
https://github.com/inboundnow/inbound-pro/releases/tag/1.9.9.8.5

**Comment by netflowauditor** [comment]
Thanks Hudson. Ill try tomorrow. Its getting a bit late in my timezone

 

From: Hudson Atwell ***@***.***>
Reply-To: inboundnow/inbound-pro ***@***.***>
Date: Tuesday, May 25, 2021 at 10:43 PM
To: inboundnow/inbound-pro ***@***.***>
Cc: netflowauditor ***@***.***>, Mention ***@***.***>
Subject: Re: [inboundnow/inbound-pro] Gutenberg 10.6.2 causes the Emails component of Inboundnow to stop using email templates (#205)

 

hi @netflowauditor

I increased the priority of one of our filters and it solves the conflict with Gutenberg.

Pushing a new release now.
